# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: N.B.
description: > # this means to ignore newlines until "baseurl:"
  Nota bene (/ˈnoʊtə ˈbɛneɪ/, /ˈnoʊtə ˈbɛni/ or /ˈnoʊtə ˈbiːni/; plural form notate bene) is a Latin phrase meaning "note well". The phrase first appeared in English writing circa 1711.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zaletniy.github.io/" # the base hostname & protocol for your site
#twitter_username: zaletniy
github_username:  zaletniy

# Build settings
markdown: kramdown
